### ISSUE TITLE
nice job, wish to add wstring & wchar_t 's interface

### ISSUE THREAD

**Issue by flosso** [zordtk/ustring#1]
thank you very much!

**Comment by zordtk** [comment]
First thanks for checking it out. I'm not quite sure what you are asking for. Are you looking for a conversion to and from wstring/wchar_t? Or for it to more follow the API of STL's string library? 

wchar_t can be differen't sizes depending on the platform, either 16bit or 32bit. That's why C++11 added u16string and u32string, which I have type conversions for.

**Comment by zordtk** [comment]
I'm closing this. If you want to discuss if further you can re-open, or send me an email.
